# Generated by Django 3.2 on 2022-08-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='Book',
            field=models.ManyToManyField(to='BookApp.Book'),
        ),
    ]
