# Generated by Django 3.2 on 2022-08-24 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0003_cartproduct_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproduct',
            name='Book',
        ),
    ]
