# Generated by Django 3.2 on 2022-08-24 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0004_remove_cartproduct_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BookApp.book'),
        ),
    ]
