# Generated by Django 3.2 on 2022-08-25 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0005_cartproduct_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproduct',
            name='user',
        ),
    ]
