# Generated by Django 3.2 on 2022-08-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0008_remove_cartproduct_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='user',
            field=models.EmailField(default=None, max_length=254, null=True),
        ),
    ]
