# Generated by Django 3.2 on 2022-08-26 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0015_auto_20220825_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.PositiveBigIntegerField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order Completed', 'Order Completed'), ('Order Processing', 'Order Processing'), ('On the way', 'On the way'), ('Order Canceled', 'Order Canceled'), ('Order Received', 'Order Received')], default='Order Received', max_length=100),
        ),
    ]
