# Generated by Django 3.2 on 2022-08-26 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0016_auto_20220827_0207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='quantity',
            new_name='totalQuantity',
        ),
    ]
