# Generated by Django 3.2 on 2022-08-26 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0018_auto_20220827_0210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='totalQuantity',
            new_name='quantity',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order Completed', 'Order Completed'), ('Order Processing', 'Order Processing'), ('Order Canceled', 'Order Canceled'), ('Order Received', 'Order Received'), ('On the way', 'On the way')], default='Order Received', max_length=100),
        ),
    ]
