# Generated by Django 3.2 on 2022-08-26 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0019_auto_20220827_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order Processing', 'Order Processing'), ('On the way', 'On the way'), ('Order Canceled', 'Order Canceled'), ('Order Received', 'Order Received'), ('Order Completed', 'Order Completed')], default='Order Received', max_length=100),
        ),
    ]
