# Generated by Django 3.2 on 2022-08-26 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0021_auto_20220827_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order Received', 'Order Received'), ('On the way', 'On the way'), ('Order Completed', 'Order Completed'), ('Order Processing', 'Order Processing'), ('Order Canceled', 'Order Canceled')], default='Order Received', max_length=100),
        ),
    ]
