# Generated by Django 3.2 on 2022-08-30 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0022_auto_20220827_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='otp',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(default=None, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('On the way', 'On the way'), ('Order Processing', 'Order Processing'), ('Order Completed', 'Order Completed'), ('Order Received', 'Order Received'), ('Order Canceled', 'Order Canceled')], default='Order Received', max_length=100),
        ),
    ]
