# Generated by Django 3.2 on 2022-08-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0026_auto_20220830_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order Received', 'Order Received'), ('Order Completed', 'Order Completed'), ('Order Processing', 'Order Processing'), ('Order Canceled', 'Order Canceled'), ('On the way', 'On the way')], default='Order Received', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='otp',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
